sudo: required
services:
  - docker

before_install:
  - docker build -t gulzi619/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run gulzi619/react-test npm test -- --coverage

after_success:
  - docker build -t gulzi619/multi-client ./client
  - docker build -t gulzi619/multi-nginx ./nginx
  - docker build -t gulzi619/multi-server ./server
  - docker build -t gulzi619/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to Docker Hub
  - docker push gulzi619/multi-client 
  - docker push gulzi619/multi-nginx
  - docker push gulzi619/multi-server
  - docker push gulzi619/multi-worker